### ISSUE TITLE
[typos] README contains multiple grammatical errors 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-library#39]
### Please describe the bug

There are multiple references to the exact same header with different content? 

https://github.com/AlaskaAirlines/auro-library/blob/04c0adbb6b08b96113c17f583949d634c32566da/README.md?plain=1#L22-L36

Also, `Versioming` is not a word. 

### Reproducing the error

None

### Expected behavior

Documentation is better defined and typos are addressed. 

### Exit criteria

This issue can be closed once the typos are addressed and the content architecture is better defined.

**Comment by fajar-apri-alaska** [comment]
Closing, since this has been resolved with https://github.com/AlaskaAirlines/auro-library/pull/50.
