### ISSUE TITLE
Update all component demo page references

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-library#49]
### General Support Request

We need to keep the naming convention for all demo pages consistent across all components. In this case, we all files for the component landing page to be named `index` and the api examples page to be named `api`.

### Possible Solution

Update all `demo.md` or `demo.html` references to `index.md` or `index.html` and update all `apiExamples.md or `apiExamples.html` to `api.md` or `api.html`.

### Additional context

These file names are being updated across all components.

**Comment by Patrick-Daly-AA** [comment]
Note: Will need to also update other components to actually used this updated script.  Doc Site will also need to be updated to take into account the new names.

**Comment by jason-capsule42** [comment]
This work is all completed by this PR that will be merged shortly
