### ISSUE TITLE
Move file placeholder text replacement scripting to it's own utility

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-library#59]
### Is your feature request related to a problem? Please describe.

`./scripts/build/generateDocs.mjs` currently has two functions in that need to be moved.

`nameExtraction()` and `formatTemplateFileContents()`.

These functions need to be used for other things besides the doc build and need to be in a separate importable class.

### Describe the solution you'd like

Move these two functions into a separate utility file in `./scripts/util`. configure the functions to accept parameters for the source file and destination location for the newly formated content. Integrate this new utility back into the generateDocs script so that it still works correctly.

### Describe alternatives you've considered

None

**Comment by DukeFerdinand** [comment]
Handlebars templating checklist
- [x] Extract template replacer functions into separate class/file
- [x] Validate extracted functions work still
- [x] Install Handlebars
- [x] Validate Handlebars can replace variables
    - [ ] Stretch goal - see if custom functions can be used for certain formatting
- [ ] Replace all variables in markdown templates with handlebars syntax - CURRENT
- [ ] Ensure all functions in `generateDocs` file are using new templteFiller class
