### ISSUE TITLE
`scripts/build/generateDocs.mjs` does not generate docs from version `2.9.0`

### ISSUE THREAD

**Issue by sun-mota** [AlaskaAirlines/auro-library#79]
### Please describe the bug

1. on any component project, upgrade `@aurodesignsystem/auro-library` module
2. Try one of following
2.1. remove `demo/index.md`
2.2. update any md file in `docs`
2.3. remove all contents in `demo/index.md`
3. run `rpm run build:docs`
4. `demo/index.md` file does not get newly generated

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

`demo/*.md` file should be generated with `npm run build:docs` command
`"build:docs": "node ./node_modules/@aurodesignsystem/auro-library/scripts/build/generateDocs.mjs",`

### Additional context

works correctly on `2.8.0`

**Comment by jason-capsule42** [comment]
This may be related to the rebuild of the generateDocs scripting that @DukeFerdinand was working on.

**Comment by jason-capsule42** [comment]
This issue is handled by other work @DukeFerdinand is already addressing
